server:
  port: 9090

spring:
  application:
    name: gateway
  main:
    banner-mode: off
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: security
          uri: lb://security-management
          predicates:
            - Path= /security/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - StripPrefix=1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/
    should-unregister-on-shutdown: true
  instance:
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
  metrics:
    export:
      prometheus:
        pushgateway:
          enabled: true