server:
  port: 9003

logging:
  level:
    com.zaxxer.hikari: TRACE
    org.hibernate.SQL: debug
    org.hibernate.type: trace
spring:
  cloud:
    config:
      enabled: false
  flyway:
    enabled: true
    locations: "classpath:/db/migration"
    default-schema: SEC
    schemas: SEC
  sql:
    init:
      encoding: UTF-8
      mode: always
      continue-on-error: false
  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    url: jdbc:h2:file:~/h2/securitydb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    hikari:
      allow-pool-suspension: true
      register-mbeans: true
      maximum-pool-size: 100
      minimum-idle: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: sec
      hibernate.dialect: 'org.hibernate.dialect.H2Dialect'

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: 127.0.0.1
    eureka-server-port: 8000
    enabled: true
  instance:
    hostname: localhost
    prefer-ip-address: true