server:
  port: 8050

logging:
  level:
    com.zaxxer.hikari: TRACE
    org.hibernate.SQL: debug
    org.hibernate.type: trace
spring:
  cloud:
    config:
      enabled: false
  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    url: jdbc:h2:tcp://localhost:9002/mem:testdb;SCHEMA=test
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    hikari:
      allow-pool-suspension: true
      register-mbeans: true
      maximum-pool-size: 100
      minimum-idle: 10


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: 127.0.0.1
    eureka-server-port: 8000
    enabled: true
  instance:
    hostname: localhost
    prefer-ip-address: true