server:
  port: 8050

logging:
  level:
    com.zaxxer.hikari: TRACE
    org.hibernate.SQL: debug
    org.hibernate.type: trace
spring:
  application:
    name: resource-service
  cloud:
    config:
      enabled: false
  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    hikari:
      allow-pool-suspension: true
      register-mbeans: true
      maximum-pool-size: 100
      minimum-idle: 10

eureka:
  client:
    enabled: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka/
    eureka-server-port: 8000
  instance:
    hostname: localhost
    prefer-ip-address: true