server:
  port: 8050

spring:
  cloud:
      config:
        enabled: false
  application:
    name: service1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    registry-fetch-interval-seconds: 5000
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3