CREATE SCHEMA IF NOT EXISTS test;
CREATE USER IF NOT EXISTS test PASSWORD 'test' ADMIN;
CREATE SEQUENCE IF NOT EXISTS test.HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 50;

CREATE TABLE test.APP_USER
(
    ID                 NUMBER(19) GENERATED ALWAYS AS IDENTITY (INCREMENT BY 1 CACHE 50),
    USERNAME           VARCHAR(20) NOT NULL UNIQUE,
    PASSWORD           VARCHAR(80) NOT NULL,
    OWNER_ID           NUMBER(19) NOT NULL,
    ENABLED            NUMBER(1) DEFAULT 1 NOT NULL,
    LOCKED             NUMBER(1) DEFAULT 0 NOT NULL,
    CREDENTIAL_EXPIRED NUMBER(1) DEFAULT 0 NOT NULL,
    DELETED            NUMBER(1) DEFAULT 0 NOT NULL,
    VERSION            NUMBER(10) DEFAULT 0 NOT NULL
);